# ----------------------------------------------------------------------------
#       _____
#      *     *
#     *____   *____
#    * *===*   *==*
#   *___*===*___**  AVNET
#        *======*
#         *====*
# ----------------------------------------------------------------------------
# 
#  This design is the property of Avnet.  Publication of this
#  design is not authorized without written consent from Avnet.
# 
#  Please direct any questions or issues to the MicroZed Community Forums:
#      http://www.microzed.org
# 
#  Disclaimer:
#     Avnet, Inc. makes no warranty for the use of this code or design.
#     This code is provided  "As Is". Avnet, Inc assumes no responsibility for
#     any errors, which may appear in this code, nor does it make a commitment
#     to update the information contained herein. Avnet, Inc specifically
#     disclaims any implied warranties of fitness for a particular purpose.
#                      Copyright(c) 2014 Avnet, Inc.
#                              All rights reserved.
# 
# ----------------------------------------------------------------------------
# 
#  Create Date:         December 02, 2014
#  Design Name:         
#  Module Name:         
#  Project Name:        
#  Target Devices:      Zynq-7010
#  Hardware Boards:     MicroZed, IO Carrier
# 
#  Tool versions:       Vivado 2014.4
# 
#  Description:         Build Script for MicroZed IO Carrier
# 
#  Dependencies:        To be called from a project build script
# 
# ----------------------------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[53]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[52]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[51]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[50]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[49]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[48]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[47]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[46]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[45]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[44]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[43]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[42]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[41]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[40]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ddr_vrn]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ddr_vrp]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_clk]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_porb]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_srstb]
set_property IOSTANDARD LVCMOS33 [get_ports M_AXI_GP0_ACLK]
set_property DONT_TOUCH true [get_cells design_1_i/processing_system7_0/U0]
set_property DONT_TOUCH true [get_cells design_1_i/processing_system7_0]
set_property DONT_TOUCH true [get_cells design_1_i]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_ba[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_ba[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_ba[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dm[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dm[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dqs_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dqs_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dqs_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dqs_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dqs_p[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dqs_p[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dqs_p[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DDR_dqs_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_cas_n]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_ck_n]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_ck_p]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_cke]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_odt]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_ras_n]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports DDR_we_n]
set_property SLEW SLOW [get_ports {DDR_addr[14]}]
set_property SLEW SLOW [get_ports {DDR_addr[13]}]
set_property SLEW SLOW [get_ports {DDR_addr[12]}]
set_property SLEW SLOW [get_ports {DDR_addr[11]}]
set_property SLEW SLOW [get_ports {DDR_addr[10]}]
set_property SLEW SLOW [get_ports {DDR_addr[9]}]
set_property SLEW SLOW [get_ports {DDR_addr[8]}]
set_property SLEW SLOW [get_ports {DDR_addr[7]}]
set_property SLEW SLOW [get_ports {DDR_addr[6]}]
set_property SLEW SLOW [get_ports {DDR_addr[5]}]
set_property SLEW SLOW [get_ports {DDR_addr[4]}]
set_property SLEW SLOW [get_ports {DDR_addr[3]}]
set_property SLEW SLOW [get_ports {DDR_addr[2]}]
set_property SLEW SLOW [get_ports {DDR_addr[1]}]
set_property SLEW SLOW [get_ports {DDR_addr[0]}]
set_property SLEW SLOW [get_ports {DDR_ba[2]}]
set_property SLEW SLOW [get_ports {DDR_ba[1]}]
set_property SLEW SLOW [get_ports {DDR_ba[0]}]
set_property SLEW SLOW [get_ports {DDR_dm[3]}]
set_property SLEW SLOW [get_ports {DDR_dm[2]}]
set_property SLEW SLOW [get_ports {DDR_dm[1]}]
set_property SLEW SLOW [get_ports {DDR_dm[0]}]
set_property SLEW SLOW [get_ports {DDR_dq[31]}]
set_property SLEW SLOW [get_ports {DDR_dq[30]}]
set_property SLEW SLOW [get_ports {DDR_dq[29]}]
set_property SLEW SLOW [get_ports {DDR_dq[28]}]
set_property SLEW SLOW [get_ports {DDR_dq[27]}]
set_property SLEW SLOW [get_ports {DDR_dq[26]}]
set_property SLEW SLOW [get_ports {DDR_dq[25]}]
set_property SLEW SLOW [get_ports {DDR_dq[24]}]
set_property SLEW SLOW [get_ports {DDR_dq[23]}]
set_property SLEW SLOW [get_ports {DDR_dq[22]}]
set_property SLEW SLOW [get_ports {DDR_dq[21]}]
set_property SLEW SLOW [get_ports {DDR_dq[20]}]
set_property SLEW SLOW [get_ports {DDR_dq[19]}]
set_property SLEW SLOW [get_ports {DDR_dq[18]}]
set_property SLEW SLOW [get_ports {DDR_dq[17]}]
set_property SLEW SLOW [get_ports {DDR_dq[16]}]
set_property SLEW SLOW [get_ports {DDR_dq[15]}]
set_property SLEW SLOW [get_ports {DDR_dq[14]}]
set_property SLEW SLOW [get_ports {DDR_dq[13]}]
set_property SLEW SLOW [get_ports {DDR_dq[12]}]
set_property SLEW SLOW [get_ports {DDR_dq[11]}]
set_property SLEW SLOW [get_ports {DDR_dq[10]}]
set_property SLEW SLOW [get_ports {DDR_dq[9]}]
set_property SLEW SLOW [get_ports {DDR_dq[8]}]
set_property SLEW SLOW [get_ports {DDR_dq[7]}]
set_property SLEW SLOW [get_ports {DDR_dq[6]}]
set_property SLEW SLOW [get_ports {DDR_dq[5]}]
set_property SLEW SLOW [get_ports {DDR_dq[4]}]
set_property SLEW SLOW [get_ports {DDR_dq[3]}]
set_property SLEW SLOW [get_ports {DDR_dq[2]}]
set_property SLEW SLOW [get_ports {DDR_dq[1]}]
set_property SLEW SLOW [get_ports {DDR_dq[0]}]
set_property SLEW SLOW [get_ports {DDR_dqs_n[3]}]
set_property SLEW SLOW [get_ports {DDR_dqs_n[2]}]
set_property SLEW SLOW [get_ports {DDR_dqs_n[1]}]
set_property SLEW SLOW [get_ports {DDR_dqs_n[0]}]
set_property SLEW SLOW [get_ports {DDR_dqs_p[3]}]
set_property SLEW SLOW [get_ports {DDR_dqs_p[2]}]
set_property SLEW SLOW [get_ports {DDR_dqs_p[1]}]
set_property SLEW SLOW [get_ports {DDR_dqs_p[0]}]
set_property SLEW SLOW [get_ports DDR_cas_n]
set_property SLEW SLOW [get_ports DDR_ck_n]
set_property SLEW SLOW [get_ports DDR_ck_p]
set_property SLEW SLOW [get_ports DDR_cke]
set_property SLEW SLOW [get_ports DDR_cs_n]
set_property SLEW SLOW [get_ports DDR_odt]
set_property SLEW SLOW [get_ports DDR_ras_n]
set_property SLEW SLOW [get_ports DDR_reset_n]
set_property SLEW SLOW [get_ports DDR_we_n]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[53]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[52]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[51]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[50]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[49]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[48]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[47]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[46]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[45]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[44]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[43]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[42]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[41]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[40]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[39]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[38]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[37]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[36]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[35]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[34]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[33]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[32]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[31]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[30]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[29]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[28]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[27]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[26]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[25]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[24]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[23]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[22]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[21]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[20]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[19]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[18]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[17]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[16]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[15]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[14]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[13]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[12]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[11]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[10]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[9]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[8]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[7]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[6]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[5]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[4]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[3]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[2]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[1]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[0]}]
set_property SLEW SLOW [get_ports FIXED_IO_ddr_vrn]
set_property SLEW SLOW [get_ports FIXED_IO_ddr_vrp]
set_property SLEW SLOW [get_ports FIXED_IO_ps_clk]
set_property SLEW SLOW [get_ports FIXED_IO_ps_porb]
set_property SLEW SLOW [get_ports FIXED_IO_ps_srstb]
set_property PACKAGE_PIN K17 [get_ports {M_AXI_GP0_ACLK}]; 